//
// Created by Xiong on 2016/9/19.
//
/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>

/* Header for class com_hc_config_Initializer */

#ifndef _FLZX_ASSETS_H
#define _FLZX_ASSETS_H
#ifdef __cplusplus
extern "C" {
#endif

jbyteArray JNICALL assets_decode(JNIEnv *env,jclass clazz, jbyteArray bytes);
jbyteArray JNICALL assets_decodeOffset(JNIEnv *env,jclass clazz, jbyteArray bytes,jint offset,jint length);
jint JNICALL assets_keyLength(JNIEnv *env,jclass clazz);

#ifdef __cplusplus
}
#endif
#endif
