//
// Created by Xiong on 2016/9/19.
//
/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_hc_config_Initializer */

#ifndef _FLZX_Initializer
#define _FLZX_Initializer
#ifdef __cplusplus
extern "C" {
#endif

/* This function will be call when the library first be load.
* You can do some init in the libray. return which version jni it support.
*/
JNIEXPORT jint JNI_OnLoad(JavaVM* vm, void* reserved);

#ifdef __cplusplus
}
#endif
#endif

